{
  gROOT->SetBatch();
  gStyle->SetOptStat(0);
  TFile *fFL = new TFile("results/hypothesis_FL.root");
  TFile *fLL = new TFile("results/hypothesis_LL.root");
  TFile *fBG = new TFile("results/hypothesis_BG.root");
  const double FLxsection = 1.218;
  const double LLxsection = 1.229;
  const double BGxsection = 127100.;
  const double FLEvt = 81215.;
  const double LLEvt = 81262.;
  const double BGEvt = 900789.;
  const double FLScale = FLxsection / FLEvt; //0.00001499
  const double LLScale = LLxsection / LLEvt; //0.00001512
  const double BGScale = BGxsection / BGEvt; //0.1411
  double maxi = 0;

  TCanvas *cEventCounter = new TCanvas("cEventCounter","EventCounter",800,500);
  gPad->SetLogy();
  TH1F* EventCounterFL = (TH1F*)fFL->Get("EventCounter");
  EventCounterFL->SetLineColor(2);
  EventCounterFL->Scale(FLScale);
  TH1F* EventCounterLL = (TH1F*)fLL->Get("EventCounter");
  EventCounterLL->SetLineColor(3);
  EventCounterLL->Scale(LLScale);
  TH1F* EventCounterBG = (TH1F*)fBG->Get("EventCounter");
  EventCounterBG->SetLineColor(4);
  EventCounterBG->Scale(BGScale);
  maxi = EventCounterBG->GetMaximum();
  EventCounterBG->GetYaxis()->SetRangeUser(1e-2,maxi*3.);
  TLegend *lEventCounter = new TLegend(0.8,0.8,1.,1.);
  lEventCounter->AddEntry(EventCounterFL,"FL","l");
  lEventCounter->AddEntry(EventCounterLL,"LL","l");
  lEventCounter->AddEntry(EventCounterBG,"BG","l");
  EventCounterBG->Draw("");
  EventCounterFL->Draw("same");
  EventCounterLL->Draw("same");
  lEventCounter->Draw();
  cEventCounter->Draw();
  cEventCounter->SaveAs("plots/hypothesis/EventCounter_Scaled.pdf");

  TCanvas *cTopdR = new TCanvas("cTopdR","Top DeltaR",800,500);
  gPad->SetLogy();
  TH1F* TopdRFL = (TH1F*)fFL->Get("TopdR");
  TopdRFL->SetLineColor(2);
  TopdRFL->Scale(FLScale);
  TH1F* TopdRLL = (TH1F*)fLL->Get("TopdR");
  TopdRLL->SetLineColor(3);
  TopdRLL->Scale(LLScale);
  TH1F* TopdRBG = (TH1F*)fBG->Get("TopdR");
  TopdRBG->SetLineColor(4);
  TopdRBG->Scale(BGScale);
  maxi = TopdRBG->GetMaximum();
  TopdRBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lTopdR = new TLegend(0.8,0.8,1.,1.);
  lTopdR->AddEntry(TopdRFL,"FL","l");
  lTopdR->AddEntry(TopdRLL,"LL","l");
  lTopdR->AddEntry(TopdRBG,"BG","l");
  TopdRBG->Draw("");
  TopdRFL->Draw("same");
  TopdRLL->Draw("same");
  lTopdR->Draw();
  cTopdR->Draw();
  cTopdR->SaveAs("plots/hypothesis/TopdR_Scaled.pdf");

  TCanvas *cTopPtDiff = new TCanvas("cTopPtDiff","Top Pt Difference",800,500);
  gPad->SetLogy();
  TH1F* TopPtDiffFL = (TH1F*)fFL->Get("TopPtDiff");
  TopPtDiffFL->SetLineColor(2);
  TopPtDiffFL->Scale(FLScale);
  TH1F* TopPtDiffLL = (TH1F*)fLL->Get("TopPtDiff");
  TopPtDiffLL->SetLineColor(3);
  TopPtDiffLL->Scale(LLScale);
  TH1F* TopPtDiffBG = (TH1F*)fBG->Get("TopPtDiff");
  TopPtDiffBG->SetLineColor(4);
  TopPtDiffBG->Scale(BGScale);
  maxi = TopPtDiffBG->GetMaximum();
  TopPtDiffBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lTopPtDiff = new TLegend(0.8,0.8,1.,1.);
  lTopPtDiff->AddEntry(TopPtDiffFL,"FL","l");
  lTopPtDiff->AddEntry(TopPtDiffLL,"LL","l");
  lTopPtDiff->AddEntry(TopPtDiffBG,"BG","l");
  TopPtDiffBG->Draw("");
  TopPtDiffFL->Draw("same");
  TopPtDiffLL->Draw("same");
  lTopPtDiff->Draw();
  cTopPtDiff->Draw();
  cTopPtDiff->SaveAs("plots/hypothesis/TopPtDiff_Scaled.pdf");

  TCanvas *cWPTPt = new TCanvas("cWPTPt","t from W'(hadronic in BG) Pt",800,500);
  gPad->SetLogy();
  TH1F* WPTPtFL = (TH1F*)fFL->Get("WPTPt");
  WPTPtFL->SetLineColor(2);
  WPTPtFL->Scale(FLScale);
  TH1F* WPTPtLL = (TH1F*)fLL->Get("WPTPt");
  WPTPtLL->SetLineColor(3);
  WPTPtLL->Scale(LLScale);
  TH1F* WPTPtBG = (TH1F*)fBG->Get("WPTPt");
  WPTPtBG->SetLineColor(4);
  WPTPtBG->Scale(BGScale);
  maxi = WPTPtBG->GetMaximum();
  WPTPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPTPt = new TLegend(0.8,0.8,1.,1.);
  lWPTPt->AddEntry(WPTPtFL,"FL","l");
  lWPTPt->AddEntry(WPTPtLL,"LL","l");
  lWPTPt->AddEntry(WPTPtBG,"BG","l");
  WPTPtBG->Draw("");
  WPTPtFL->Draw("same");
  WPTPtLL->Draw("same");
  lWPTPt->Draw();
  cWPTPt->Draw();
  cWPTPt->SaveAs("plots/hypothesis/WPTPt_Scaled.pdf");

  TCanvas *cOtTPt = new TCanvas("cOtTPt","t not from W'(leptonic in BG)",800,500);
  gPad->SetLogy();
  TH1F* OtTPtFL = (TH1F*)fFL->Get("OtTPt");
  OtTPtFL->SetLineColor(2);
  OtTPtFL->Scale(FLScale);
  TH1F* OtTPtLL = (TH1F*)fLL->Get("OtTPt");
  OtTPtLL->SetLineColor(3);
  OtTPtLL->Scale(LLScale);
  TH1F* OtTPtBG = (TH1F*)fBG->Get("OtTPt");
  OtTPtBG->SetLineColor(4);
  OtTPtBG->Scale(BGScale);
  maxi = OtTPtBG->GetMaximum();
  OtTPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lOtTPt = new TLegend(0.8,0.8,1.,1.);
  lOtTPt->AddEntry(OtTPtFL,"FL","l");
  lOtTPt->AddEntry(OtTPtLL,"LL","l");
  lOtTPt->AddEntry(OtTPtBG,"BG","l");
  OtTPtBG->Draw("");
  OtTPtFL->Draw("same");
  OtTPtLL->Draw("same");
  lOtTPt->Draw();
  cOtTPt->Draw();
  cOtTPt->SaveAs("plots/hypothesis/OtTPt_Scaled.pdf");

  TCanvas *cWdR = new TCanvas("cWdR","W DeltaR",800,500);
  gPad->SetLogy();
  TH1F* WdRFL = (TH1F*)fFL->Get("WdR");
  WdRFL->SetLineColor(2);
  WdRFL->Scale(FLScale);
  TH1F* WdRLL = (TH1F*)fLL->Get("WdR");
  WdRLL->SetLineColor(3);
  WdRLL->Scale(LLScale);
  TH1F* WdRBG = (TH1F*)fBG->Get("WdR");
  WdRBG->SetLineColor(4);
  WdRBG->Scale(BGScale);
  maxi = WdRBG->GetMaximum();
  WdRBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWdR = new TLegend(0.8,0.8,1.,1.);
  lWdR->AddEntry(WdRFL,"FL","l");
  lWdR->AddEntry(WdRLL,"LL","l");
  lWdR->AddEntry(WdRBG,"BG","l");
  WdRBG->Draw("");
  WdRFL->Draw("same");
  WdRLL->Draw("same");
  lWdR->Draw();
  cWdR->Draw();
  cWdR->SaveAs("plots/hypothesis/WdR_Scaled.pdf");

  TCanvas *cWPtDiff = new TCanvas("cWPtDiff","W Pt differnece",800,500);
  gPad->SetLogy();
  TH1F* WPtDiffFL = (TH1F*)fFL->Get("WPtDiff");
  WPtDiffFL->SetLineColor(2);
  WPtDiffFL->Scale(FLScale);
  TH1F* WPtDiffLL = (TH1F*)fLL->Get("WPtDiff");
  WPtDiffLL->SetLineColor(3);
  WPtDiffLL->Scale(LLScale);
  TH1F* WPtDiffBG = (TH1F*)fBG->Get("WPtDiff");
  WPtDiffBG->SetLineColor(4);
  WPtDiffBG->Scale(BGScale);
  maxi = WPtDiffBG->GetMaximum();
  WPtDiffBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPtDiff = new TLegend(0.8,0.8,1.,1.);
  lWPtDiff->AddEntry(WPtDiffFL,"FL","l");
  lWPtDiff->AddEntry(WPtDiffLL,"LL","l");
  lWPtDiff->AddEntry(WPtDiffBG,"BG","l");
  WPtDiffBG->Draw("");
  WPtDiffFL->Draw("same");
  WPtDiffLL->Draw("same");
  lWPtDiff->Draw();
  cWPtDiff->Draw();
  cWPtDiff->SaveAs("plots/hypothesis/WPtDiff_Scaled.pdf");

  TCanvas *cWPBPt = new TCanvas("cWPBPt","b from W' Pt",800,500);
  gPad->SetLogy();
  TH1F* WPBPtFL = (TH1F*)fFL->Get("WPBPt");
  WPBPtFL->SetLineColor(2);
  WPBPtFL->Scale(FLScale);
  TH1F* WPBPtLL = (TH1F*)fLL->Get("WPBPt");
  WPBPtLL->SetLineColor(3);
  WPBPtLL->Scale(LLScale);
  TH1F* WPBPtBG = (TH1F*)fBG->Get("WPBPt");
  WPBPtBG->SetLineColor(4);
  WPBPtBG->Scale(BGScale);
  maxi = WPBPtBG->GetMaximum();
  WPBPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPBPt = new TLegend(0.8,0.8,1.,1.);
  lWPBPt->AddEntry(WPBPtFL,"FL","l");
  lWPBPt->AddEntry(WPBPtLL,"LL","l");
  lWPBPt->AddEntry(WPBPtBG,"BG","l");
  WPBPtBG->Draw("");
  WPBPtFL->Draw("same");
  WPBPtLL->Draw("same");
  lWPBPt->Draw();
  cWPBPt->Draw();
  cWPBPt->SaveAs("plots/hypothesis/WPBPt_Scaled.pdf");

  TCanvas *cWPTBPt = new TCanvas("cWPTBPt","b from t from W' Pt(hadronic in BG)",800,500);
  gPad->SetLogy();
  TH1F* WPTBPtFL = (TH1F*)fFL->Get("WPTBPt");
  WPTBPtFL->SetLineColor(2);
  WPTBPtFL->Scale(FLScale);
  TH1F* WPTBPtLL = (TH1F*)fLL->Get("WPTBPt");
  WPTBPtLL->SetLineColor(3);
  WPTBPtLL->Scale(LLScale);
  TH1F* WPTBPtBG = (TH1F*)fBG->Get("WPTBPt");
  WPTBPtBG->SetLineColor(4);
  WPTBPtBG->Scale(BGScale);
  maxi = WPTBPtBG->GetMaximum();
  WPTBPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPTBPt = new TLegend(0.8,0.8,1.,1.);
  lWPTBPt->AddEntry(WPTBPtFL,"FL","l");
  lWPTBPt->AddEntry(WPTBPtLL,"LL","l");
  lWPTBPt->AddEntry(WPTBPtBG,"BG","l");
  WPTBPtBG->Draw("");
  WPTBPtFL->Draw("same");
  WPTBPtLL->Draw("same");
  lWPTBPt->Draw();
  cWPTBPt->Draw();
  cWPTBPt->SaveAs("plots/hypothesis/WPTBPt_Scaled.pdf");

  TCanvas *cOtTBPt = new TCanvas("cOtTBPt","b from other t Pt(leptonic in BG)",800,500);
  gPad->SetLogy();
  TH1F* OtTBPtFL = (TH1F*)fFL->Get("OtTBPt");
  OtTBPtFL->SetLineColor(2);
  OtTBPtFL->Scale(FLScale);
  TH1F* OtTBPtLL = (TH1F*)fLL->Get("OtTBPt");
  OtTBPtLL->SetLineColor(3);
  OtTBPtLL->Scale(LLScale);
  TH1F* OtTBPtBG = (TH1F*)fBG->Get("OtTBPt");
  OtTBPtBG->SetLineColor(4);
  OtTBPtBG->Scale(BGScale);
  maxi = OtTBPtBG->GetMaximum();
  OtTBPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lOtTBPt = new TLegend(0.8,0.8,1.,1.);
  lOtTBPt->AddEntry(OtTBPtFL,"FL","l");
  lOtTBPt->AddEntry(OtTBPtLL,"LL","l");
  lOtTBPt->AddEntry(OtTBPtBG,"BG","l");
  OtTBPtBG->Draw("");
  OtTBPtFL->Draw("same");
  OtTBPtLL->Draw("same");
  lOtTBPt->Draw();
  cOtTBPt->Draw();
  cOtTBPt->SaveAs("plots/hypothesis/OtTBPt_Scaled.pdf");

  TCanvas *cLFPt = new TCanvas("cLFPt","Hadronic decay product Pt",800,500);
  gPad->SetLogy();
  TH1F* LFPtFL = (TH1F*)fFL->Get("LFPt");
  LFPtFL->SetLineColor(2);
  LFPtFL->Scale(FLScale);
  TH1F* LFPtLL = (TH1F*)fLL->Get("LFPt");
  LFPtLL->SetLineColor(3);
  LFPtLL->Scale(LLScale);
  TH1F* LFPtBG = (TH1F*)fBG->Get("LFPt");
  LFPtBG->SetLineColor(4);
  LFPtBG->Scale(BGScale);
  maxi = LFPtBG->GetMaximum();
  LFPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lLFPt = new TLegend(0.8,0.8,1.,1.);
  lLFPt->AddEntry(LFPtFL,"FL","l");
  lLFPt->AddEntry(LFPtLL,"LL","l");
  lLFPt->AddEntry(LFPtBG,"BG","l");
  LFPtBG->Draw("");
  LFPtFL->Draw("same");
  LFPtLL->Draw("same");
  lLFPt->Draw();
  cLFPt->Draw();
  cLFPt->SaveAs("plots/hypothesis/LFPt_Scaled.pdf");

  TCanvas *cWPBLeading = new TCanvas("cWPBLeading","If b from W' is leading",800,500);
  gPad->SetLogy();
  TH1F* WPBLeadingFL = (TH1F*)fFL->Get("WPBLeading");
  WPBLeadingFL->SetLineColor(2);
  WPBLeadingFL->Scale(FLScale);
  TH1F* WPBLeadingLL = (TH1F*)fLL->Get("WPBLeading");
  WPBLeadingLL->SetLineColor(3);
  WPBLeadingLL->Scale(LLScale);
  TH1F* WPBLeadingBG = (TH1F*)fBG->Get("WPBLeading");
  WPBLeadingBG->SetLineColor(4);
  WPBLeadingBG->Scale(BGScale);
  maxi = WPBLeadingBG->GetMaximum();
  WPBLeadingBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPBLeading = new TLegend(0.8,0.8,1.,1.);
  lWPBLeading->AddEntry(WPBLeadingFL,"FL","l");
  lWPBLeading->AddEntry(WPBLeadingLL,"LL","l");
  lWPBLeading->AddEntry(WPBLeadingBG,"BG","l");
  WPBLeadingLL->Draw("");
  WPBLeadingFL->Draw("same");
  WPBLeadingBG->Draw("same");
  lWPBLeading->Draw();
  cWPBLeading->Draw();
  cWPBLeading->SaveAs("plots/hypothesis/WPBLeading_Scaled.pdf");

  TCanvas *cJetNumber = new TCanvas("cJetNumber","If b from W' is leading",800,500);
  gPad->SetLogy();
  TH1F* JetNumberFL = (TH1F*)fFL->Get("JetNumber");
  JetNumberFL->SetLineColor(2);
  JetNumberFL->Scale(FLScale);
  TH1F* JetNumberLL = (TH1F*)fLL->Get("JetNumber");
  JetNumberLL->SetLineColor(3);
  JetNumberLL->Scale(LLScale);
  TH1F* JetNumberBG = (TH1F*)fBG->Get("JetNumber");
  JetNumberBG->SetLineColor(4);
  JetNumberBG->Scale(BGScale);
  maxi = JetNumberBG->GetMaximum();
  JetNumberBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lJetNumber = new TLegend(0.8,0.8,1.,1.);
  lJetNumber->AddEntry(JetNumberFL,"FL","l");
  lJetNumber->AddEntry(JetNumberLL,"LL","l");
  lJetNumber->AddEntry(JetNumberBG,"BG","l");
  JetNumberBG->Draw("");
  JetNumberFL->Draw("same");
  JetNumberLL->Draw("same");
  lJetNumber->Draw();
  cJetNumber->Draw();
  cJetNumber->SaveAs("plots/hypothesis/JetNumber_Scaled.pdf");

  TCanvas *cBJetNumber = new TCanvas("cBJetNumber","If b from W' is leading",800,500);
  gPad->SetLogy();
  TH1F* BJetNumberFL = (TH1F*)fFL->Get("BJetNumber");
  BJetNumberFL->SetLineColor(2);
  BJetNumberFL->Scale(FLScale);
  TH1F* BJetNumberLL = (TH1F*)fLL->Get("BJetNumber");
  BJetNumberLL->SetLineColor(3);
  BJetNumberLL->Scale(LLScale);
  TH1F* BJetNumberBG = (TH1F*)fBG->Get("BJetNumber");
  BJetNumberBG->SetLineColor(4);
  BJetNumberBG->Scale(BGScale);
  maxi = BJetNumberBG->GetMaximum();
  BJetNumberBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lBJetNumber = new TLegend(0.8,0.8,1.,1.);
  lBJetNumber->AddEntry(BJetNumberFL,"FL","l");
  lBJetNumber->AddEntry(BJetNumberLL,"LL","l");
  lBJetNumber->AddEntry(BJetNumberBG,"BG","l");
  BJetNumberBG->Draw("");
  BJetNumberFL->Draw("same");
  BJetNumberLL->Draw("same");
  lBJetNumber->Draw();
  cBJetNumber->Draw();
  cBJetNumber->SaveAs("plots/hypothesis/BJetNumber_Scaled.pdf");

  TCanvas *cNBJetNumber = new TCanvas("cNBJetNumber","If b from W' is leading",800,500);
  gPad->SetLogy();
  TH1F* NBJetNumberFL = (TH1F*)fFL->Get("NBJetNumber");
  NBJetNumberFL->SetLineColor(2);
  NBJetNumberFL->Scale(FLScale);
  TH1F* NBJetNumberLL = (TH1F*)fLL->Get("NBJetNumber");
  NBJetNumberLL->SetLineColor(3);
  NBJetNumberLL->Scale(LLScale);
  TH1F* NBJetNumberBG = (TH1F*)fBG->Get("NBJetNumber");
  NBJetNumberBG->SetLineColor(4);
  NBJetNumberBG->Scale(BGScale);
  maxi = NBJetNumberBG->GetMaximum();
  NBJetNumberBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lNBJetNumber = new TLegend(0.8,0.8,1.,1.);
  lNBJetNumber->AddEntry(NBJetNumberFL,"FL","l");
  lNBJetNumber->AddEntry(NBJetNumberLL,"LL","l");
  lNBJetNumber->AddEntry(NBJetNumberBG,"BG","l");
  NBJetNumberBG->Draw("");
  NBJetNumberFL->Draw("same");
  NBJetNumberLL->Draw("same");
  lNBJetNumber->Draw();
  cNBJetNumber->Draw();
  cNBJetNumber->SaveAs("plots/hypothesis/NBJetNumber_Scaled.pdf");

  TCanvas *cLeadingIsB = new TCanvas("cLeadingIsB","If leading jet is a b-jet",800,500);
  gPad->SetLogy();
  TH1F* LeadingIsBFL = (TH1F*)fFL->Get("LeadingIsB");
  LeadingIsBFL->SetLineColor(2);
  LeadingIsBFL->Scale(FLScale);
  TH1F* LeadingIsBLL = (TH1F*)fLL->Get("LeadingIsB");
  LeadingIsBLL->SetLineColor(3);
  LeadingIsBLL->Scale(LLScale);
  TH1F* LeadingIsBBG = (TH1F*)fBG->Get("LeadingIsB");
  LeadingIsBBG->SetLineColor(4);
  LeadingIsBBG->Scale(BGScale);
  maxi = LeadingIsBBG->GetMaximum();
  LeadingIsBBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lLeadingIsB = new TLegend(0.8,0.8,1.,1.);
  lLeadingIsB->AddEntry(LeadingIsBFL,"FL","l");
  lLeadingIsB->AddEntry(LeadingIsBLL,"LL","l");
  lLeadingIsB->AddEntry(LeadingIsBBG,"BG","l");
  LeadingIsBBG->Draw("");
  LeadingIsBFL->Draw("same");
  LeadingIsBLL->Draw("same");
  lLeadingIsB->Draw();
  cLeadingIsB->Draw();
  cLeadingIsB->SaveAs("plots/hypothesis/LeadingIsB_Scaled.pdf");

  TCanvas *cWPBDiffLeading = new TCanvas("cWPBDiffLeading","W' b minus other leading parton",800,500);
  gPad->SetLogy();
  TH1F* WPBDiffLeadingFL = (TH1F*)fFL->Get("WPBDiffLeading");
  WPBDiffLeadingFL->SetLineColor(2);
  WPBDiffLeadingFL->Scale(FLScale);
  TH1F* WPBDiffLeadingLL = (TH1F*)fLL->Get("WPBDiffLeading");
  WPBDiffLeadingLL->SetLineColor(3);
  WPBDiffLeadingLL->Scale(LLScale);
  TH1F* WPBDiffLeadingBG = (TH1F*)fBG->Get("WPBDiffLeading");
  WPBDiffLeadingBG->SetLineColor(4);
  WPBDiffLeadingBG->Scale(BGScale);
  maxi = WPBDiffLeadingBG->GetMaximum();
  WPBDiffLeadingBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPBDiffLeading = new TLegend(0.8,0.8,1.,1.);
  lWPBDiffLeading->AddEntry(WPBDiffLeadingFL,"FL","l");
  lWPBDiffLeading->AddEntry(WPBDiffLeadingLL,"LL","l");
  lWPBDiffLeading->AddEntry(WPBDiffLeadingBG,"BG","l");
  WPBDiffLeadingBG->Draw("");
  WPBDiffLeadingFL->Draw("same");
  WPBDiffLeadingLL->Draw("same");
  lWPBDiffLeading->Draw();
  cWPBDiffLeading->Draw();
  cWPBDiffLeading->SaveAs("plots/hypothesis/WPBDiffLeading_Scaled.pdf");

  TCanvas *cWPBDiffLeadingB = new TCanvas("cWPBDiffLeadingB","W' b minus other leading b",800,500);
  gPad->SetLogy();
  TH1F* WPBDiffLeadingBFL = (TH1F*)fFL->Get("WPBDiffLeadingB");
  WPBDiffLeadingBFL->SetLineColor(2);
  WPBDiffLeadingBFL->Scale(FLScale);
  TH1F* WPBDiffLeadingBLL = (TH1F*)fLL->Get("WPBDiffLeadingB");
  WPBDiffLeadingBLL->SetLineColor(3);
  WPBDiffLeadingBLL->Scale(LLScale);
  TH1F* WPBDiffLeadingBBG = (TH1F*)fBG->Get("WPBDiffLeadingB");
  WPBDiffLeadingBBG->SetLineColor(4);
  WPBDiffLeadingBBG->Scale(BGScale);
  maxi = WPBDiffLeadingBBG->GetMaximum();
  WPBDiffLeadingBBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPBDiffLeadingB = new TLegend(0.8,0.8,1.,1.);
  lWPBDiffLeadingB->AddEntry(WPBDiffLeadingBFL,"FL","l");
  lWPBDiffLeadingB->AddEntry(WPBDiffLeadingBLL,"LL","l");
  lWPBDiffLeadingB->AddEntry(WPBDiffLeadingBBG,"BG","l");
  WPBDiffLeadingBBG->Draw("");
  WPBDiffLeadingBFL->Draw("same");
  WPBDiffLeadingBLL->Draw("same");
  lWPBDiffLeadingB->Draw();
  cWPBDiffLeadingB->Draw();
  cWPBDiffLeadingB->SaveAs("plots/hypothesis/WPBDiffLeadingB_Scaled.pdf");

  TCanvas *cWPTBDiffOtB = new TCanvas("cWPTBDiffOtB","W'-t-b minus the other t-b",800,500);
  gPad->SetLogy();
  TH1F* WPTBDiffOtBFL = (TH1F*)fFL->Get("WPTBDiffOtB");
  WPTBDiffOtBFL->SetLineColor(2);
  WPTBDiffOtBFL->Scale(FLScale);
  TH1F* WPTBDiffOtBLL = (TH1F*)fLL->Get("WPTBDiffOtB");
  WPTBDiffOtBLL->SetLineColor(3);
  WPTBDiffOtBLL->Scale(LLScale);
  TH1F* WPTBDiffOtBBG = (TH1F*)fBG->Get("WPTBDiffOtB");
  WPTBDiffOtBBG->SetLineColor(4);
  WPTBDiffOtBBG->Scale(BGScale);
  maxi = WPTBDiffOtBBG->GetMaximum();
  WPTBDiffOtBBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lWPTBDiffOtB = new TLegend(0.8,0.8,1.,1.);
  lWPTBDiffOtB->AddEntry(WPTBDiffOtBFL,"FL","l");
  lWPTBDiffOtB->AddEntry(WPTBDiffOtBLL,"LL","l");
  lWPTBDiffOtB->AddEntry(WPTBDiffOtBBG,"BG","l");
  WPTBDiffOtBBG->Draw("");
  WPTBDiffOtBFL->Draw("same");
  WPTBDiffOtBLL->Draw("same");
  lWPTBDiffOtB->Draw();
  cWPTBDiffOtB->Draw();
  cWPTBDiffOtB->SaveAs("plots/hypothesis/WPTBDiffOtB_Scaled.pdf");

  TCanvas *cTPtMinusLepPt = new TCanvas("cTPtMinusLepPt","W'-t-b minus the other t-b",800,500);
  gPad->SetLogy();
  TH1F* TPtMinusLepPtFL = (TH1F*)fFL->Get("TPtMinusLepPt");
  TPtMinusLepPtFL->SetLineColor(2);
  TPtMinusLepPtFL->Scale(FLScale);
  TH1F* TPtMinusLepPtLL = (TH1F*)fLL->Get("TPtMinusLepPt");
  TPtMinusLepPtLL->SetLineColor(3);
  TPtMinusLepPtLL->Scale(LLScale);
  TH1F* TPtMinusLepPtBG = (TH1F*)fBG->Get("TPtMinusLepPt");
  TPtMinusLepPtBG->SetLineColor(4);
  TPtMinusLepPtBG->Scale(BGScale);
  maxi = TPtMinusLepPtBG->GetMaximum();
  TPtMinusLepPtBG->GetYaxis()->SetRangeUser(1e-6,maxi*3.);
  TLegend *lTPtMinusLepPt = new TLegend(0.8,0.8,1.,1.);
  lTPtMinusLepPt->AddEntry(TPtMinusLepPtFL,"FL","l");
  lTPtMinusLepPt->AddEntry(TPtMinusLepPtLL,"LL","l");
  lTPtMinusLepPt->AddEntry(TPtMinusLepPtBG,"BG","l");
  TPtMinusLepPtBG->Draw("");
  TPtMinusLepPtFL->Draw("same");
  TPtMinusLepPtLL->Draw("same");
  lTPtMinusLepPt->Draw();
  cTPtMinusLepPt->Draw();
  cTPtMinusLepPt->SaveAs("plots/hypothesis/TPtMinusLepPt_Scaled.pdf");

  TCanvas *cNBJetsVsBJetsFL = new TCanvas("cNBJetsVsBJetsFL","Leptonic t Pt Vs MET Pt(FL)",800,500);
  gPad->SetLogz();
  TH2F* NBJetsVsBJetsFL = (TH2F*)fFL->Get("NBJetsVsBJets");
  NBJetsVsBJetsFL->Draw("colz");
  cNBJetsVsBJetsFL->SaveAs("plots/hypothesis/NBJetsVsBJetsFL.pdf");

  TCanvas *cNBJetsVsBJetsLL = new TCanvas("cNBJetsVsBJetsLL","Leptonic t Pt Vs MET Pt(LL)",800,500);
  gPad->SetLogz();
  TH2F* NBJetsVsBJetsLL = (TH2F*)fLL->Get("NBJetsVsBJets");
  NBJetsVsBJetsLL->Draw("colz");
  cNBJetsVsBJetsLL->SaveAs("plots/hypothesis/NBJetsVsBJetsLL.pdf");

  TCanvas *cNBJetsVsBJetsBG = new TCanvas("cNBJetsVsBJetsBG","Leptonic t Pt Vs MET Pt(BG)",800,500);
  gPad->SetLogz();
  TH2F* NBJetsVsBJetsBG = (TH2F*)fBG->Get("NBJetsVsBJets");
  NBJetsVsBJetsBG->Draw("colz");
  cNBJetsVsBJetsBG->SaveAs("plots/hypothesis/NBJetsVsBJetsBG.pdf");

  TCanvas *cWPBDiffTBFL = new TCanvas("cWPBDiffTBFL","W' b minus t-b(FL)",800,500);
  TH2F* WPBDiffTBFL = (TH2F*)fFL->Get("WPBDiffTB");
  WPBDiffTBFL->Draw("colz");
  cWPBDiffTBFL->SaveAs("plots/hypothesis/WPBDiffTBFL.pdf");

  TCanvas *cWPBDiffTBLL = new TCanvas("cWPBDiffTBLL","W' b minus t-b(LL)",800,500);
  TH2F* WPBDiffTBLL = (TH2F*)fLL->Get("WPBDiffTB");
  WPBDiffTBLL->Draw("colz");
  cWPBDiffTBLL->SaveAs("plots/hypothesis/WPBDiffTBLL.pdf");

  TCanvas *cTPtVsLepPtFL = new TCanvas("cTPtVsLepPtFL","Leptonic t Pt Vs lepton Pt(FL)",800,500);
  TH2F* TPtVsLepPtFL = (TH2F*)fFL->Get("TPtVsLepPt");
  TPtVsLepPtFL->Draw("colz");
  cTPtVsLepPtFL->SaveAs("plots/hypothesis/TPtVsLepPtFL.pdf");

  TCanvas *cTPtVsLepPtLL = new TCanvas("cTPtVsLepPtLL","Leptonic t Pt Vs lepton Pt(LL)",800,500);
  TH2F* TPtVsLepPtLL = (TH2F*)fLL->Get("TPtVsLepPt");
  TPtVsLepPtLL->Draw("colz");
  cTPtVsLepPtLL->SaveAs("plots/hypothesis/TPtVsLepPtLL.pdf");

  TCanvas *cTPtVsLepPtBG = new TCanvas("cTPtVsLepPtBG","Leptonic t Pt Vs lepton Pt(BG)",800,500);
  TH2F* TPtVsLepPtBG = (TH2F*)fBG->Get("TPtVsLepPt");
  TPtVsLepPtBG->Draw("colz");
  cTPtVsLepPtBG->SaveAs("plots/hypothesis/TPtVsLepPtBG.pdf");

  TCanvas *cTPtVsMETPtFL = new TCanvas("cTPtVsMETPtFL","Leptonic t Pt Vs MET Pt(FL)",800,500);
  TH2F* TPtVsMETPtFL = (TH2F*)fFL->Get("TPtVsMETPt");
  TPtVsMETPtFL->Draw("colz");
  cTPtVsMETPtFL->SaveAs("plots/hypothesis/TPtVsMETPtFL.pdf");

  TCanvas *cTPtVsMETPtLL = new TCanvas("cTPtVsMETPtLL","Leptonic t Pt Vs MET Pt(LL)",800,500);
  TH2F* TPtVsMETPtLL = (TH2F*)fLL->Get("TPtVsMETPt");
  TPtVsMETPtLL->Draw("colz");
  cTPtVsMETPtLL->SaveAs("plots/hypothesis/TPtVsMETPtLL.pdf");

  TCanvas *cTPtVsMETPtBG = new TCanvas("cTPtVsMETPtBG","Leptonic t Pt Vs MET Pt(BG)",800,500);
  TH2F* TPtVsMETPtBG = (TH2F*)fBG->Get("TPtVsMETPt");
  TPtVsMETPtBG->Draw("colz");
  cTPtVsMETPtBG->SaveAs("plots/hypothesis/TPtVsMETPtBG.pdf");

}
