{
  gROOT->SetBatch();
  gStyle->SetOptStat(0);
  TFile *fFL = new TFile("results/hypothesis_FL.root");
  TFile *fLL = new TFile("results/hypothesis_LL.root");
  TFile *fBG = new TFile("results/hypothesis_BG.root");

  TCanvas *cEventCounter = new TCanvas("cEventCounter","EventCounter",800,500);
  TH1F* EventCounterFL = (TH1F*)fFL->Get("EventCounter");
  EventCounterFL->SetLineColor(2);
  TH1F* EventCounterLL = (TH1F*)fLL->Get("EventCounter");
  EventCounterLL->SetLineColor(3);
  TH1F* EventCounterBG = (TH1F*)fBG->Get("EventCounter");
  EventCounterBG->SetLineColor(4);
  TLegend *lEventCounter = new TLegend(0.8,0.8,1.,1.);
  lEventCounter->AddEntry(EventCounterFL,"FL","l");
  lEventCounter->AddEntry(EventCounterLL,"LL","l");
  lEventCounter->AddEntry(EventCounterBG,"BG","l");
  EventCounterBG->Draw("");
  EventCounterFL->Draw("same");
  EventCounterLL->Draw("same");
  lEventCounter->Draw();
  cEventCounter->Draw();
  cEventCounter->SaveAs("plots/hypothesis/EventCounter.pdf");

  TCanvas *cTopdR = new TCanvas("cTopdR","Top DeltaR",800,500);
  TH1F* TopdRFL = (TH1F*)fFL->Get("TopdR");
  TopdRFL->SetLineColor(2);
  TH1F* TopdRLL = (TH1F*)fLL->Get("TopdR");
  TopdRLL->SetLineColor(3);
  TH1F* TopdRBG = (TH1F*)fBG->Get("TopdR");
  TopdRBG->SetLineColor(4);
  TLegend *lTopdR = new TLegend(0.8,0.8,1.,1.);
  lTopdR->AddEntry(TopdRFL,"FL","l");
  lTopdR->AddEntry(TopdRLL,"LL","l");
  lTopdR->AddEntry(TopdRBG,"BG","l");
  TopdRBG->DrawNormalized("");
  TopdRFL->DrawNormalized("same");
  TopdRLL->DrawNormalized("same");
  lTopdR->Draw();
  cTopdR->Draw();
  cTopdR->SaveAs("plots/hypothesis/TopdR.pdf");

  TCanvas *cTopPtDiff = new TCanvas("cTopPtDiff","Top Pt Difference",800,500);
  TH1F* TopPtDiffFL = (TH1F*)fFL->Get("TopPtDiff");
  TopPtDiffFL->SetLineColor(2);
  TH1F* TopPtDiffLL = (TH1F*)fLL->Get("TopPtDiff");
  TopPtDiffLL->SetLineColor(3);
  TH1F* TopPtDiffBG = (TH1F*)fBG->Get("TopPtDiff");
  TopPtDiffBG->SetLineColor(4);
  TLegend *lTopPtDiff = new TLegend(0.8,0.8,1.,1.);
  lTopPtDiff->AddEntry(TopPtDiffFL,"FL","l");
  lTopPtDiff->AddEntry(TopPtDiffLL,"LL","l");
  lTopPtDiff->AddEntry(TopPtDiffBG,"BG","l");
  TopPtDiffBG->DrawNormalized("");
  TopPtDiffFL->DrawNormalized("same");
  TopPtDiffLL->DrawNormalized("same");
  lTopPtDiff->Draw();
  cTopPtDiff->Draw();
  cTopPtDiff->SaveAs("plots/hypothesis/TopPtDiff.pdf");

  TCanvas *cWPTPt = new TCanvas("cWPTPt","t from W'(hadronic in BG) Pt",800,500);
  TH1F* WPTPtFL = (TH1F*)fFL->Get("WPTPt");
  WPTPtFL->SetLineColor(2);
  TH1F* WPTPtLL = (TH1F*)fLL->Get("WPTPt");
  WPTPtLL->SetLineColor(3);
  TH1F* WPTPtBG = (TH1F*)fBG->Get("WPTPt");
  WPTPtBG->SetLineColor(4);
  TLegend *lWPTPt = new TLegend(0.8,0.8,1.,1.);
  lWPTPt->AddEntry(WPTPtFL,"FL","l");
  lWPTPt->AddEntry(WPTPtLL,"LL","l");
  lWPTPt->AddEntry(WPTPtBG,"BG","l");
  WPTPtBG->DrawNormalized("");
  WPTPtFL->DrawNormalized("same");
  WPTPtLL->DrawNormalized("same");
  lWPTPt->Draw();
  cWPTPt->Draw();
  cWPTPt->SaveAs("plots/hypothesis/WPTPt.pdf");

  TCanvas *cOtTPt = new TCanvas("cOtTPt","t not from W'(leptonic in BG)",800,500);
  TH1F* OtTPtFL = (TH1F*)fFL->Get("OtTPt");
  OtTPtFL->SetLineColor(2);
  TH1F* OtTPtLL = (TH1F*)fLL->Get("OtTPt");
  OtTPtLL->SetLineColor(3);
  TH1F* OtTPtBG = (TH1F*)fBG->Get("OtTPt");
  OtTPtBG->SetLineColor(4);
  TLegend *lOtTPt = new TLegend(0.8,0.8,1.,1.);
  lOtTPt->AddEntry(OtTPtFL,"FL","l");
  lOtTPt->AddEntry(OtTPtLL,"LL","l");
  lOtTPt->AddEntry(OtTPtBG,"BG","l");
  OtTPtBG->DrawNormalized("");
  OtTPtFL->DrawNormalized("same");
  OtTPtLL->DrawNormalized("same");
  lOtTPt->Draw();
  cOtTPt->Draw();
  cOtTPt->SaveAs("plots/hypothesis/OtTPt.pdf");

  TCanvas *cWdR = new TCanvas("cWdR","W DeltaR",800,500);
  TH1F* WdRFL = (TH1F*)fFL->Get("WdR");
  WdRFL->SetLineColor(2);
  TH1F* WdRLL = (TH1F*)fLL->Get("WdR");
  WdRLL->SetLineColor(3);
  TH1F* WdRBG = (TH1F*)fBG->Get("WdR");
  WdRBG->SetLineColor(4);
  TLegend *lWdR = new TLegend(0.8,0.8,1.,1.);
  lWdR->AddEntry(WdRFL,"FL","l");
  lWdR->AddEntry(WdRLL,"LL","l");
  lWdR->AddEntry(WdRBG,"BG","l");
  WdRBG->DrawNormalized("");
  WdRFL->DrawNormalized("same");
  WdRLL->DrawNormalized("same");
  lWdR->Draw();
  cWdR->Draw();
  cWdR->SaveAs("plots/hypothesis/WdR.pdf");

  TCanvas *cWPtDiff = new TCanvas("cWPtDiff","W Pt differnece",800,500);
  TH1F* WPtDiffFL = (TH1F*)fFL->Get("WPtDiff");
  WPtDiffFL->SetLineColor(2);
  TH1F* WPtDiffLL = (TH1F*)fLL->Get("WPtDiff");
  WPtDiffLL->SetLineColor(3);
  TH1F* WPtDiffBG = (TH1F*)fBG->Get("WPtDiff");
  WPtDiffBG->SetLineColor(4);
  TLegend *lWPtDiff = new TLegend(0.8,0.8,1.,1.);
  lWPtDiff->AddEntry(WPtDiffFL,"FL","l");
  lWPtDiff->AddEntry(WPtDiffLL,"LL","l");
  lWPtDiff->AddEntry(WPtDiffBG,"BG","l");
  WPtDiffBG->DrawNormalized("");
  WPtDiffFL->DrawNormalized("same");
  WPtDiffLL->DrawNormalized("same");
  lWPtDiff->Draw();
  cWPtDiff->Draw();
  cWPtDiff->SaveAs("plots/hypothesis/WPtDiff.pdf");

  TCanvas *cWPBPt = new TCanvas("cWPBPt","b from W' Pt",800,500);
  TH1F* WPBPtFL = (TH1F*)fFL->Get("WPBPt");
  WPBPtFL->SetLineColor(2);
  TH1F* WPBPtLL = (TH1F*)fLL->Get("WPBPt");
  WPBPtLL->SetLineColor(3);
  TH1F* WPBPtBG = (TH1F*)fBG->Get("WPBPt");
  WPBPtBG->SetLineColor(4);
  TLegend *lWPBPt = new TLegend(0.8,0.8,1.,1.);
  lWPBPt->AddEntry(WPBPtFL,"FL","l");
  lWPBPt->AddEntry(WPBPtLL,"LL","l");
  lWPBPt->AddEntry(WPBPtBG,"BG","l");
  WPBPtBG->DrawNormalized("");
  WPBPtFL->DrawNormalized("same");
  WPBPtLL->DrawNormalized("same");
  lWPBPt->Draw();
  cWPBPt->Draw();
  cWPBPt->SaveAs("plots/hypothesis/WPBPt.pdf");

  TCanvas *cWPTBPt = new TCanvas("cWPTBPt","b from t from W' Pt(hadronic in BG)",800,500);
  TH1F* WPTBPtFL = (TH1F*)fFL->Get("WPTBPt");
  WPTBPtFL->SetLineColor(2);
  TH1F* WPTBPtLL = (TH1F*)fLL->Get("WPTBPt");
  WPTBPtLL->SetLineColor(3);
  TH1F* WPTBPtBG = (TH1F*)fBG->Get("WPTBPt");
  WPTBPtBG->SetLineColor(4);
  TLegend *lWPTBPt = new TLegend(0.8,0.8,1.,1.);
  lWPTBPt->AddEntry(WPTBPtFL,"FL","l");
  lWPTBPt->AddEntry(WPTBPtLL,"LL","l");
  lWPTBPt->AddEntry(WPTBPtBG,"BG","l");
  WPTBPtBG->DrawNormalized("");
  WPTBPtFL->DrawNormalized("same");
  WPTBPtLL->DrawNormalized("same");
  lWPTBPt->Draw();
  cWPTBPt->Draw();
  cWPTBPt->SaveAs("plots/hypothesis/WPTBPt.pdf");

  TCanvas *cOtTBPt = new TCanvas("cOtTBPt","b from other t Pt(leptonic in BG)",800,500);
  TH1F* OtTBPtFL = (TH1F*)fFL->Get("OtTBPt");
  OtTBPtFL->SetLineColor(2);
  TH1F* OtTBPtLL = (TH1F*)fLL->Get("OtTBPt");
  OtTBPtLL->SetLineColor(3);
  TH1F* OtTBPtBG = (TH1F*)fBG->Get("OtTBPt");
  OtTBPtBG->SetLineColor(4);
  TLegend *lOtTBPt = new TLegend(0.8,0.8,1.,1.);
  lOtTBPt->AddEntry(OtTBPtFL,"FL","l");
  lOtTBPt->AddEntry(OtTBPtLL,"LL","l");
  lOtTBPt->AddEntry(OtTBPtBG,"BG","l");
  OtTBPtBG->DrawNormalized("");
  OtTBPtFL->DrawNormalized("same");
  OtTBPtLL->DrawNormalized("same");
  lOtTBPt->Draw();
  cOtTBPt->Draw();
  cOtTBPt->SaveAs("plots/hypothesis/OtTBPt.pdf");

  TCanvas *cLFPt = new TCanvas("cLFPt","Hadronic decay product Pt",800,500);
  TH1F* LFPtFL = (TH1F*)fFL->Get("LFPt");
  LFPtFL->SetLineColor(2);
  TH1F* LFPtLL = (TH1F*)fLL->Get("LFPt");
  LFPtLL->SetLineColor(3);
  TH1F* LFPtBG = (TH1F*)fBG->Get("LFPt");
  LFPtBG->SetLineColor(4);
  TLegend *lLFPt = new TLegend(0.8,0.8,1.,1.);
  lLFPt->AddEntry(LFPtFL,"FL","l");
  lLFPt->AddEntry(LFPtLL,"LL","l");
  lLFPt->AddEntry(LFPtBG,"BG","l");
  LFPtBG->DrawNormalized("");
  LFPtFL->DrawNormalized("same");
  LFPtLL->DrawNormalized("same");
  lLFPt->Draw();
  cLFPt->Draw();
  cLFPt->SaveAs("plots/hypothesis/LFPt.pdf");

  TCanvas *cWPBLeading = new TCanvas("cWPBLeading","If b from W' is leading",800,500);
  TH1F* WPBLeadingFL = (TH1F*)fFL->Get("WPBLeading");
  WPBLeadingFL->SetLineColor(2);
  TH1F* WPBLeadingLL = (TH1F*)fLL->Get("WPBLeading");
  WPBLeadingLL->SetLineColor(3);
  TH1F* WPBLeadingBG = (TH1F*)fBG->Get("WPBLeading");
  WPBLeadingBG->SetLineColor(4);
  TLegend *lWPBLeading = new TLegend(0.8,0.8,1.,1.);
  lWPBLeading->AddEntry(WPBLeadingFL,"FL","l");
  lWPBLeading->AddEntry(WPBLeadingLL,"LL","l");
  lWPBLeading->AddEntry(WPBLeadingBG,"BG","l");
  WPBLeadingLL->DrawNormalized("");
  WPBLeadingFL->DrawNormalized("same");
  WPBLeadingBG->DrawNormalized("same");
  lWPBLeading->Draw();
  cWPBLeading->Draw();
  cWPBLeading->SaveAs("plots/hypothesis/WPBLeading.pdf");

  TCanvas *cJetNumber = new TCanvas("cJetNumber","If b from W' is leading",800,500);
  TH1F* JetNumberFL = (TH1F*)fFL->Get("JetNumber");
  JetNumberFL->SetLineColor(2);
  TH1F* JetNumberLL = (TH1F*)fLL->Get("JetNumber");
  JetNumberLL->SetLineColor(3);
  TH1F* JetNumberBG = (TH1F*)fBG->Get("JetNumber");
  JetNumberBG->SetLineColor(4);
  TLegend *lJetNumber = new TLegend(0.8,0.8,1.,1.);
  lJetNumber->AddEntry(JetNumberFL,"FL","l");
  lJetNumber->AddEntry(JetNumberLL,"LL","l");
  lJetNumber->AddEntry(JetNumberBG,"BG","l");
  JetNumberBG->DrawNormalized("");
  JetNumberFL->DrawNormalized("same");
  JetNumberLL->DrawNormalized("same");
  lJetNumber->Draw();
  cJetNumber->Draw();
  cJetNumber->SaveAs("plots/hypothesis/JetNumber.pdf");

  TCanvas *cBJetNumber = new TCanvas("cBJetNumber","If b from W' is leading",800,500);
  TH1F* BJetNumberFL = (TH1F*)fFL->Get("BJetNumber");
  BJetNumberFL->SetLineColor(2);
  TH1F* BJetNumberLL = (TH1F*)fLL->Get("BJetNumber");
  BJetNumberLL->SetLineColor(3);
  TH1F* BJetNumberBG = (TH1F*)fBG->Get("BJetNumber");
  BJetNumberBG->SetLineColor(4);
  TLegend *lBJetNumber = new TLegend(0.8,0.8,1.,1.);
  lBJetNumber->AddEntry(BJetNumberFL,"FL","l");
  lBJetNumber->AddEntry(BJetNumberLL,"LL","l");
  lBJetNumber->AddEntry(BJetNumberBG,"BG","l");
  BJetNumberBG->DrawNormalized("");
  BJetNumberFL->DrawNormalized("same");
  BJetNumberLL->DrawNormalized("same");
  lBJetNumber->Draw();
  cBJetNumber->Draw();
  cBJetNumber->SaveAs("plots/hypothesis/BJetNumber.pdf");

  TCanvas *cNBJetNumber = new TCanvas("cNBJetNumber","If b from W' is leading",800,500);
  TH1F* NBJetNumberFL = (TH1F*)fFL->Get("NBJetNumber");
  NBJetNumberFL->SetLineColor(2);
  TH1F* NBJetNumberLL = (TH1F*)fLL->Get("NBJetNumber");
  NBJetNumberLL->SetLineColor(3);
  TH1F* NBJetNumberBG = (TH1F*)fBG->Get("NBJetNumber");
  NBJetNumberBG->SetLineColor(4);
  TLegend *lNBJetNumber = new TLegend(0.8,0.8,1.,1.);
  lNBJetNumber->AddEntry(NBJetNumberFL,"FL","l");
  lNBJetNumber->AddEntry(NBJetNumberLL,"LL","l");
  lNBJetNumber->AddEntry(NBJetNumberBG,"BG","l");
  NBJetNumberBG->DrawNormalized("");
  NBJetNumberFL->DrawNormalized("same");
  NBJetNumberLL->DrawNormalized("same");
  lNBJetNumber->Draw();
  cNBJetNumber->Draw();
  cNBJetNumber->SaveAs("plots/hypothesis/NBJetNumber.pdf");

  TCanvas *cLeadingIsB = new TCanvas("cLeadingIsB","If leading jet is a b-jet",800,500);
  TH1F* LeadingIsBFL = (TH1F*)fFL->Get("LeadingIsB");
  LeadingIsBFL->SetLineColor(2);
  TH1F* LeadingIsBLL = (TH1F*)fLL->Get("LeadingIsB");
  LeadingIsBLL->SetLineColor(3);
  TH1F* LeadingIsBBG = (TH1F*)fBG->Get("LeadingIsB");
  LeadingIsBBG->SetLineColor(4);
  TLegend *lLeadingIsB = new TLegend(0.8,0.8,1.,1.);
  lLeadingIsB->AddEntry(LeadingIsBFL,"FL","l");
  lLeadingIsB->AddEntry(LeadingIsBLL,"LL","l");
  lLeadingIsB->AddEntry(LeadingIsBBG,"BG","l");
  LeadingIsBBG->DrawNormalized("");
  LeadingIsBFL->DrawNormalized("same");
  LeadingIsBLL->DrawNormalized("same");
  lLeadingIsB->Draw();
  cLeadingIsB->Draw();
  cLeadingIsB->SaveAs("plots/hypothesis/LeadingIsB.pdf");

  TCanvas *cWPBDiffLeading = new TCanvas("cWPBDiffLeading","W' b minus other leading parton",800,500);
  TH1F* WPBDiffLeadingFL = (TH1F*)fFL->Get("WPBDiffLeading");
  WPBDiffLeadingFL->SetLineColor(2);
  TH1F* WPBDiffLeadingLL = (TH1F*)fLL->Get("WPBDiffLeading");
  WPBDiffLeadingLL->SetLineColor(3);
  TH1F* WPBDiffLeadingBG = (TH1F*)fBG->Get("WPBDiffLeading");
  WPBDiffLeadingBG->SetLineColor(4);
  TLegend *lWPBDiffLeading = new TLegend(0.8,0.8,1.,1.);
  lWPBDiffLeading->AddEntry(WPBDiffLeadingFL,"FL","l");
  lWPBDiffLeading->AddEntry(WPBDiffLeadingLL,"LL","l");
  lWPBDiffLeading->AddEntry(WPBDiffLeadingBG,"BG","l");
  WPBDiffLeadingBG->DrawNormalized("");
  WPBDiffLeadingFL->DrawNormalized("same");
  WPBDiffLeadingLL->DrawNormalized("same");
  lWPBDiffLeading->Draw();
  cWPBDiffLeading->Draw();
  cWPBDiffLeading->SaveAs("plots/hypothesis/WPBDiffLeading.pdf");

  TCanvas *cWPBDiffLeadingB = new TCanvas("cWPBDiffLeadingB","W' b minus other leading b",800,500);
  TH1F* WPBDiffLeadingBFL = (TH1F*)fFL->Get("WPBDiffLeadingB");
  WPBDiffLeadingBFL->SetLineColor(2);
  TH1F* WPBDiffLeadingBLL = (TH1F*)fLL->Get("WPBDiffLeadingB");
  WPBDiffLeadingBLL->SetLineColor(3);
  TH1F* WPBDiffLeadingBBG = (TH1F*)fBG->Get("WPBDiffLeadingB");
  WPBDiffLeadingBBG->SetLineColor(4);
  TLegend *lWPBDiffLeadingB = new TLegend(0.8,0.8,1.,1.);
  lWPBDiffLeadingB->AddEntry(WPBDiffLeadingBFL,"FL","l");
  lWPBDiffLeadingB->AddEntry(WPBDiffLeadingBLL,"LL","l");
  lWPBDiffLeadingB->AddEntry(WPBDiffLeadingBBG,"BG","l");
  WPBDiffLeadingBBG->DrawNormalized("");
  WPBDiffLeadingBFL->DrawNormalized("same");
  WPBDiffLeadingBLL->DrawNormalized("same");
  lWPBDiffLeadingB->Draw();
  cWPBDiffLeadingB->Draw();
  cWPBDiffLeadingB->SaveAs("plots/hypothesis/WPBDiffLeadingB.pdf");

  TCanvas *cWPTBDiffOtB = new TCanvas("cWPTBDiffOtB","W'-t-b minus the other t-b",800,500);
  TH1F* WPTBDiffOtBFL = (TH1F*)fFL->Get("WPTBDiffOtB");
  WPTBDiffOtBFL->SetLineColor(2);
  TH1F* WPTBDiffOtBLL = (TH1F*)fLL->Get("WPTBDiffOtB");
  WPTBDiffOtBLL->SetLineColor(3);
  TH1F* WPTBDiffOtBBG = (TH1F*)fBG->Get("WPTBDiffOtB");
  WPTBDiffOtBBG->SetLineColor(4);
  TLegend *lWPTBDiffOtB = new TLegend(0.8,0.8,1.,1.);
  lWPTBDiffOtB->AddEntry(WPTBDiffOtBFL,"FL","l");
  lWPTBDiffOtB->AddEntry(WPTBDiffOtBLL,"LL","l");
  lWPTBDiffOtB->AddEntry(WPTBDiffOtBBG,"BG","l");
  WPTBDiffOtBBG->DrawNormalized("");
  WPTBDiffOtBFL->DrawNormalized("same");
  WPTBDiffOtBLL->DrawNormalized("same");
  lWPTBDiffOtB->Draw();
  cWPTBDiffOtB->Draw();
  cWPTBDiffOtB->SaveAs("plots/hypothesis/WPTBDiffOtB.pdf");

  TCanvas *cTPtMinusLepPt = new TCanvas("cTPtMinusLepPt","W'-t-b minus the other t-b",800,500);
  TH1F* TPtMinusLepPtFL = (TH1F*)fFL->Get("TPtMinusLepPt");
  TPtMinusLepPtFL->SetLineColor(2);
  TH1F* TPtMinusLepPtLL = (TH1F*)fLL->Get("TPtMinusLepPt");
  TPtMinusLepPtLL->SetLineColor(3);
  TH1F* TPtMinusLepPtBG = (TH1F*)fBG->Get("TPtMinusLepPt");
  TPtMinusLepPtBG->SetLineColor(4);
  TLegend *lTPtMinusLepPt = new TLegend(0.8,0.8,1.,1.);
  lTPtMinusLepPt->AddEntry(TPtMinusLepPtFL,"FL","l");
  lTPtMinusLepPt->AddEntry(TPtMinusLepPtLL,"LL","l");
  lTPtMinusLepPt->AddEntry(TPtMinusLepPtBG,"BG","l");
  TPtMinusLepPtBG->DrawNormalized("");
  TPtMinusLepPtFL->DrawNormalized("same");
  TPtMinusLepPtLL->DrawNormalized("same");
  lTPtMinusLepPt->Draw();
  cTPtMinusLepPt->Draw();
  cTPtMinusLepPt->SaveAs("plots/hypothesis/TPtMinusLepPt.pdf");

  TCanvas *cNBJetsVsBJetsFL = new TCanvas("cNBJetsVsBJetsFL","## of b-jet VS non-b-jet (FL)",800,500);
  TH2F* NBJetsVsBJetsFL = (TH2F*)fFL->Get("NBJetsVsBJets");
  NBJetsVsBJetsFL->Draw("colz");
  cNBJetsVsBJetsFL->SaveAs("plots/hypothesis/NBJetsVsBJetsFL.pdf");

  TCanvas *cNBJetsVsBJetsLL = new TCanvas("cNBJetsVsBJetsLL","## of b-jet VS non-b-jet (LL)",800,500);
  TH2F* NBJetsVsBJetsLL = (TH2F*)fLL->Get("NBJetsVsBJets");
  NBJetsVsBJetsLL->Draw("colz");
  cNBJetsVsBJetsLL->SaveAs("plots/hypothesis/NBJetsVsBJetsLL.pdf");

  TCanvas *cNBJetsVsBJetsBG = new TCanvas("cNBJetsVsBJetsBG","## of b-jet VS non-b-jet (BG)",800,500);
  TH2F* NBJetsVsBJetsBG = (TH2F*)fBG->Get("NBJetsVsBJets");
  NBJetsVsBJetsBG->Draw("colz");
  cNBJetsVsBJetsBG->SaveAs("plots/hypothesis/NBJetsVsBJetsBG.pdf");

  TCanvas *cWPBDiffTBFL = new TCanvas("cWPBDiffTBFL","W' b minus t-b(FL)",800,500);
  TH2F* WPBDiffTBFL = (TH2F*)fFL->Get("WPBDiffTB");
  WPBDiffTBFL->Draw("colz");
  cWPBDiffTBFL->SaveAs("plots/hypothesis/WPBDiffTBFL.pdf");

  TCanvas *cWPBDiffTBLL = new TCanvas("cWPBDiffTBLL","W' b minus t-b(LL)",800,500);
  TH2F* WPBDiffTBLL = (TH2F*)fLL->Get("WPBDiffTB");
  WPBDiffTBLL->Draw("colz");
  cWPBDiffTBLL->SaveAs("plots/hypothesis/WPBDiffTBLL.pdf");

  TCanvas *cTPtVsLepPtFL = new TCanvas("cTPtVsLepPtFL","Leptonic t Pt Vs lepton Pt(FL)",800,500);
  TH2F* TPtVsLepPtFL = (TH2F*)fFL->Get("TPtVsLepPt");
  TPtVsLepPtFL->Draw("colz");
  cTPtVsLepPtFL->SaveAs("plots/hypothesis/TPtVsLepPtFL.pdf");

  TCanvas *cTPtVsLepPtLL = new TCanvas("cTPtVsLepPtLL","Leptonic t Pt Vs lepton Pt(LL)",800,500);
  TH2F* TPtVsLepPtLL = (TH2F*)fLL->Get("TPtVsLepPt");
  TPtVsLepPtLL->Draw("colz");
  cTPtVsLepPtLL->SaveAs("plots/hypothesis/TPtVsLepPtLL.pdf");

  TCanvas *cTPtVsLepPtBG = new TCanvas("cTPtVsLepPtBG","Leptonic t Pt Vs lepton Pt(BG)",800,500);
  TH2F* TPtVsLepPtBG = (TH2F*)fBG->Get("TPtVsLepPt");
  TPtVsLepPtBG->Draw("colz");
  cTPtVsLepPtBG->SaveAs("plots/hypothesis/TPtVsLepPtBG.pdf");

  TCanvas *cTPtVsMETPtFL = new TCanvas("cTPtVsMETPtFL","Leptonic t Pt Vs MET Pt(FL)",800,500);
  TH2F* TPtVsMETPtFL = (TH2F*)fFL->Get("TPtVsMETPt");
  TPtVsMETPtFL->Draw("colz");
  cTPtVsMETPtFL->SaveAs("plots/hypothesis/TPtVsMETPtFL.pdf");

  TCanvas *cTPtVsMETPtLL = new TCanvas("cTPtVsMETPtLL","Leptonic t Pt Vs MET Pt(LL)",800,500);
  TH2F* TPtVsMETPtLL = (TH2F*)fLL->Get("TPtVsMETPt");
  TPtVsMETPtLL->Draw("colz");
  cTPtVsMETPtLL->SaveAs("plots/hypothesis/TPtVsMETPtLL.pdf");

  TCanvas *cTPtVsMETPtBG = new TCanvas("cTPtVsMETPtBG","Leptonic t Pt Vs MET Pt(BG)",800,500);
  TH2F* TPtVsMETPtBG = (TH2F*)fBG->Get("TPtVsMETPt");
  TPtVsMETPtBG->Draw("colz");
  cTPtVsMETPtBG->SaveAs("plots/hypothesis/TPtVsMETPtBG.pdf");

}
