executable   = Submit.sh
SampleType   = 1
arguments    = $(SampleType) $(ProcID)
output       = batchlogs/$(ClusterID)_$(SampleType)_$(ProcID).out
error        = batchlogs/$(ClusterID)_$(SampleType)_$(ProcID).err
log          = batchlogs/$(ClusterID)_$(SampleType)_$(ProcID).log
universe     = vanilla
Requirements = (OpSysAndVer =?= "CentOS7")
+JobFlavour  = "workday"
periodic_remove = (time() - QDate) > (100 * 3600)
RequestCpus  = 2
queue 20
